name: Remove project branding when used as a template

on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.repository != 'jeffchasin/testingTemplate'
    # if: github.repository != 'jeffchasin/reactor-helloworld-extension-edge'
    steps:

# Deal with the source & target repos

      - name: Get current branch name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        shell: bash
        id: getBranch

      - name: Get the owner of this repo
        run: echo "::set-output name=owner::$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')"
        shell: bash
        id: getOwner

      - name: Get the repo name and convert it to lowercase
        run: echo "::set-output name=slug::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')"
        shell: bash
        id: getSlug

      - name: Get the repo name
        run: echo "::set-output name=name::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        shell: bash
        id: getName

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ steps.getBranch.outputs.branch }}

      - name: Replace owner
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "jeffchasin"
          replace: ${{ steps.getOwner.outputs.owner }}
          regex: false

      - name: Replace repo slug
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "reactor-helloworld-extension-edge"
          replace: ${{ steps.getSlug.outputs.slug }}
          regex: false

      - name: Replace repo name
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "reactor-helloworld-extension-edge"
          replace: ${{ steps.getName.outputs.name }}
          regex: false

# Apply template docs for target repo

      - name: Archive template repo README.md
        uses: canastro/copy-file-action@master
        with:
          source: "README.md"
          target: "README.template.md"

      - name: Archive template repo CODE_OF_CONDUCT.md
        uses: canastro/copy-file-action@master
        with:
          source: "CODE_OF_CONDUCT.md"
          target: "CODE_OF_CONDUCT.template.md"

      - name: Create target repo project CONTRIBUTING.md
        uses: canastro/copy-file-action@master
        with:
          source: "CONTRIBUTING.reactor.md"
          target: "CONTRIBUTING.md"

      - name: Create target repo project CODE_OF_CONDUCT.md
        uses: canastro/copy-file-action@master
        with:
          source: "CODE_OF_CONDUCT.reactor.md"
          target: "CODE_OF_CONDUCT.md"

      - name: Create target repo project README.md
        uses: canastro/copy-file-action@master
        with:
          source: "README.reactor.md"
          target: "README.md"

# Clean up and commit to target repo

      - name: Commit changes and delete this workflow
        uses: EndBug/add-and-commit@v7
        with:
          remove: '["./CONTRIBUTING.reactor.md", "./CODE_OF_CONDUCT.template.md", "./CODE_OF_CONDUCT.reactor.md", "./.github/CONTRIBUTING.md", "./.github/ISSUE_TEMPLATE.md", "./.github/PULL_REQUEST_TEMPLATE.md", "./README.template.md", "./README.reactor.md", "./.github/workflows/reactor_template.yml"]'
          message: "🚀 Ready to launch!"
          tag: 'v1.0.0 --force'
