name: Remove project branding when used as a template

on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.repository != 'jeffchasin/reactor-helloworld-extension-edge'
    steps:

      - name: Get current branch name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        shell: bash
        id: getBranch

      - name: Get the owner of this repo
        run: echo "::set-output name=owner::$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')"
        shell: bash
        id: getOwner

      - name: Get the repo name and convert it to lowercase
        run: echo "::set-output name=slug::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')"
        shell: bash
        id: getSlug

      - name: Get the repo name
        run: echo "::set-output name=name::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        shell: bash
        id: getName

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ steps.getBranch.outputs.branch }}

      - name: Replace owner
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "jeffchasin"
          replace: ${{ steps.getOwner.outputs.owner }}
          regex: false

      - name: Replace repo slug
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "reactor-helloworld-extension-edge"
          replace: ${{ steps.getSlug.outputs.slug }}
          regex: false

      - name: Replace repo name
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "reactor-helloworld-extension-edge"
          replace: ${{ steps.getName.outputs.name }}
          regex: false

      - name: Archive template README.md
        uses: canastro/copy-file-action@master
        with:
          source: "README.md"
          target: "README.template.md"

      - name: Replace with project README.md
        uses: canastro/copy-file-action@master
        with:
          source: "README.reactor.md"
          target: "README.md"

      - name: Commit changes and delete this workflow
        uses: EndBug/add-and-commit@v7
        with:
          remove: '["./.github/workflows/reactor_template.yml", "./README.reactor.md"]'
          message: "Ready to launch! 🚀"
          tag: 'v1.0.0 --force'
